#include <esc_rtso.h>

  //DECLARACIONES DEFINE
   #DEFINE IDLE_1 PIN_C0
   #DEFINE IDLE_2 PIN_C1
   #DEFINE IDLE_3 PIN_C2

   //VARIBLES A USAR
   INT CAMBIO=0;//EN FUNCION PRINCIPAL CAMBIO DE SECUENCIA
   INT EXT=0;//VAIRIABLE A CAMBIAR EN INTERRUPCOIN POR RB0
   INT FLAG=0;//VARIABLE A ENVIAR EN PUERTO RS 232
   
    #INT_EXT//DIRECTIVA INTERRUPCION PIN RB_0
   VOID EXT_ISR(VOID)
   {
      EXT=1;
   }

   #INT_RDA//DIRECTIVA INTERRUPCION RECEPCION DATO RS 232 
   VOID RDA_ISR(VOID)
   {
      #ASM
         BCF    03.5
         BCF    0X0C.5
         BCF    0X0C.1
         MOVF   0X1A,W
         MOVWF  0X2A
      #ENDASM
      
      //VARIABLE A  CAMBIAR TRAS ATENCION DE INTERRUPCION 
      IF(CAMBIO==0)
      {
      CAMBIO=1;
      }
      ELSE
      {
      CAMBIO=0;
      }  
   }
   
   #INT_TIMER2//DIRECTIVA INTERRUPCION TIMER_2
   VOID TIMER2_ISR(VOID)
   {
      //LETURA DE CONVERCION AD Y ENTRAGA A PUERTO D
      #ASM
         BSF    03.5
         MOVF   0X1E,W
         BCF    03.5
         MOVWF  0X08
         BSF    0X1F.2
      #ENDASM
   }

void main()
{
   #USE RS232(BAUD=9600, XMIT=PIN_C6, RCV=PIN_C7, BITS=8)//DIRECTIVA USO UART
   SETUP_ADC_PORTS(ALL_ANALOG);//CONFIGURAMOS TODO EL PUERTO COMO SALIDA ANALOGA
   SETUP_ADC(ADC_CLOCK_DIV_32);//CONFIGURAMOS VELOCIDAD DE CONVERSION
   SETUP_TIMER_2(T2_DIV_BY_16,255,1);//CONFIGUARMOS TIMER_2
   
   ENABLE_INTERRUPTS(INT_TIMER2);//HABILITAMOS INTERRUPCION DESBORDAMIENTO TIMER_2
   ENABLE_INTERRUPTS(INT_EXT);//HABILITAMOS INTERRUPCION PIN_B0
   ENABLE_INTERRUPTS(INT_RDA);//HABILITAMOS INTERRUPCION RECEPCION DATO RS 232
   ENABLE_INTERRUPTS(GLOBAL);//HABILITAMOS INTERRUPCIONES (GLOBALES)
   
   
   //JUSTIFICACION A LA DERECHA DE ADRESH Y ADRESL
   #ASM
      BSF    3.5
      BSF    0X1F.7
      BCF    3.5
   #ENDASM
   
   SET_ADC_CHANNEL(1);//CANAL A USAR PARA CONVERSION AN1

   //CONFIGURAMOS PUERTOS
   SET_TRIS_B(0B00000001);
   SET_TRIS_D(0);
   
   //INICIALIZAMOS SALIDAS
   OUTPUT_LOW(PIN_B1);
   OUTPUT_LOW(PIN_B2);
   OUTPUT_LOW(PIN_B3);
   OUTPUT_LOW(PIN_B4);
   OUTPUT_LOW(PIN_B5);
   OUTPUT_LOW(PIN_B6);
   OUTPUT_LOW(PIN_B7);
   OUTPUT_D(0);
   
   //INICIAMOS CONVERSION ADC
   #ASM         
      BSF    0X1F.2
   #ENDASM
   
   while(TRUE)
   {
      IF(EXT==1)//DETERMINAMOS ESTADO FLAG ATENCION INTERRUPCION POR PIN RB_0
            {
               FLAG=1;//VALOR A ENVIAR EN BUS SERIAL
               PUTC(FLAG);//ENVIAMOS DATO POR BUS SERIAL
               FLAG=0;//INICIALIZAMOS VARIABLE
               EXT=0;//BORRAMOS ESTADO FLAG INTERRUPCION
            }
  
     IF(CAMBIO==0)
     {
     //TAREA OCIOSA
     OUTPUT_LOW(IDLE_1);
     OUTPUT_LOW(IDLE_2);
     OUTPUT_LOW(IDLE_3);
     OUTPUT_HIGH(IDLE_3);
     DELAY_MS(200);
     OUTPUT_LOW(IDLE_3);
     DELAY_MS(200);
     OUTPUT_HIGH(IDLE_2);
     DELAY_MS(200);
     OUTPUT_LOW(IDLE_2);
     DELAY_MS(200);
     OUTPUT_HIGH(IDLE_1);
     DELAY_MS(200);
     OUTPUT_LOW(IDLE_1);
     DELAY_MS(200);
     }
     ELSE
     {
     //ACCION A ATENDER CON INTERRUPCION POR RB_0 (CAMBIO SECUENCIA)
     OUTPUT_LOW(IDLE_1);
     OUTPUT_LOW(IDLE_2);
     OUTPUT_LOW(IDLE_3);
     OUTPUT_HIGH(IDLE_1);
     DELAY_MS(200);
     OUTPUT_LOW(IDLE_1);
     DELAY_MS(200);
     OUTPUT_HIGH(IDLE_2);
     DELAY_MS(200);
     OUTPUT_LOW(IDLE_2);
     DELAY_MS(200);
     OUTPUT_HIGH(IDLE_3);
     DELAY_MS(200);
     OUTPUT_LOW(IDLE_3);
     DELAY_MS(200);
      }
   }

}

